baseURL = 'https://swilcox.github.io'
languageCode = 'en-us'
title = 'Steven Wilcox'
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true
timeZone = 'US/Central'

[params]
author = "swilcox"
description = "just a fleeting shadow"
github = "swilcox"
twitter = "swilcox"
linkedin = "scwilcox"
instagram = "scwilcox"
email = "steven@wilcox.be"
url = "https://wilcox.be"
keywords = "blog, git, python"
rss = true
lastmod = true
userStatusEmoji = "🫰"
favicon = "/images/github-mark.png"
avatar = "/images/scw.jpg"
headerIcon = "/images/icon.svg"
location = "TN, US"
enableGitalk = true

[params.gitalk]
clientID = "Ov23limLWzmnMLE1HJkb"
clientSecret = "c3ed7f1f857b9e8b833d97d2d93569f79fe9b257"
repo = "swilcox-gitalk-comments"
owner = "swilcox"
admin = "swilcox"
id = "location.pathname"
labels = "gitalk"
perPage = 15
pagerDirection = "last"
createIssueManually = true
distractionFreeMode = false

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[markup.goldmark.renderer]
unsafe = true
