baseURL = 'https://swilcox.github.io'
languageCode = 'en-us'
title = 'Steven Wilcox'
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true
timeZone = 'US/Central'
enableEmoji = true
copyright = "&copy;2024 by Steven Wilcox"

[params]
author = "swilcox"
description = "just a fleeting shadow"
github = "swilcox"
twitter = "swilcox"
linkedin = "scwilcox"
instagram = "scwilcox"
email = "steven@wilcox.be"
url = "https://wilcox.be"
keywords = "blog, git, python"
rss = true
lastmod = true
userStatusEmoji = "🫰"
favicon = "/images/github-mark.png"
avatar = "/images/scw.jpg"
headerIcon = "/images/icon.svg"
location = "TN, US"
enableGitalk = false

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[markup.goldmark.renderer]
unsafe = true
